spring:
  application:
    name: demo

  sql:
    init:
      schema-locations: classpath:db/schema.sql

  thymeleaf:
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    encoding: UTF-8

  datasource:
    initialization-mode: always
    url: jdbc:mariadb://database:3306/books
    username: level1
    password: level1
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto=update:
    database-platform: org.hibernate.dialect.MariaDBDialect
    naming-strategy: org.springframework.boot.orm.jpa.SpringNamingStrategy

